-- Two incorrect attempts in the same millisecond used to share the primary key
-- (target_digest, purpose, failed_at) and surface a uniqueness failure.
-- Each attempt now has its own identity so equal timestamps remain ordinary
-- failures. Callers still insert only the target, purpose, and time.
ALTER TABLE community.auth_target_failures
  ADD COLUMN failure_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE community.auth_target_failures
  DROP CONSTRAINT auth_target_failures_pkey;

ALTER TABLE community.auth_target_failures
  ADD CONSTRAINT auth_target_failures_pkey PRIMARY KEY (failure_id);

-- A verify receipt can recover one lost response while its session is live.
-- origin_session_id stays on the first session of that lineage. closed_at is
-- set by explicit logout and ends replay, including a session minted by a
-- concurrent retry. It is not a second authentication credential.
ALTER TABLE community.auth_receipts
  ADD COLUMN origin_session_id TEXT,
  ADD COLUMN closed_at TIMESTAMPTZ;

UPDATE community.auth_receipts
SET origin_session_id = session_id
WHERE origin_session_id IS NULL;

ALTER TABLE community.auth_receipts
  ALTER COLUMN origin_session_id SET NOT NULL;

ALTER TABLE community.auth_receipts
  ADD CONSTRAINT auth_receipts_origin_session CHECK (
    origin_session_id ~ '^session-[0-9a-f]{32}$'
  );

CREATE INDEX auth_receipts_origin_session_idx
  ON community.auth_receipts (origin_session_id);
