// @vitest-environment jsdom
import { act, useRef } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NotificationRefresher } from "./notification-refresher";
(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;
let node: HTMLDivElement,
  root: ReturnType<typeof createRoot>,
  scroll: HTMLDivElement;
const refresh = vi.fn<() => Promise<void>>();
const rowClick = vi.fn();
function Harness({ loading = false }: { loading?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  return (
    <div ref={ref} data-scroll="">
      <NotificationRefresher
        scrollRef={ref}
        loading={loading}
        onRefresh={refresh}
      />
      <button data-row="" onClick={rowClick}>
        Notification
      </button>
    </div>
  );
}
const state = () =>
  node
    .querySelector("[data-notification-refresh]")
    ?.getAttribute("data-notification-refresh");
async function touch(type: string, x: number, y: number, count = 1) {
  const event = new Event(type, { bubbles: true, cancelable: true });
  Object.defineProperty(event, "touches", {
    value: Array.from(
      { length: type === "touchend" || type === "touchcancel" ? 0 : count },
      (_, identifier) => ({ identifier, clientX: x, clientY: y }),
    ),
  });
  await act(async () =>
    scroll.querySelector("[data-row]")!.dispatchEvent(event),
  );
  return event;
}
async function pull(end = true) {
  await touch("touchstart", 150, 100);
  await touch("touchmove", 150, 280);
  if (end) await touch("touchend", 150, 280);
}
beforeEach(async () => {
  vi.clearAllMocks();
  refresh.mockResolvedValue(undefined);
  node = document.createElement("div");
  document.body.append(node);
  root = createRoot(node);
  await act(async () => root.render(<Harness />));
  scroll = node.querySelector("[data-scroll]")!;
  vi.spyOn(scroll, "getBoundingClientRect").mockReturnValue({
    left: 0,
    right: 390,
    top: 0,
    bottom: 800,
    width: 390,
    height: 800,
    x: 0,
    y: 0,
    toJSON: () => ({}),
  });
});
afterEach(async () => {
  await act(async () => root.unmount());
  node.remove();
  vi.restoreAllMocks();
});
describe("notification pull-to-refresh", () => {
  it("reveals progress, arms on pull and waits for one request after release", async () => {
    let finish!: () => void;
    refresh.mockImplementation(
      () =>
        new Promise((resolve) => {
          finish = resolve;
        }),
    );
    await touch("touchstart", 150, 100);
    const moved = await touch("touchmove", 150, 160);
    expect(moved.defaultPrevented).toBe(true);
    expect(state()).toBe("pulling");
    expect(refresh).not.toHaveBeenCalled();
    await touch("touchmove", 150, 280);
    expect(state()).toBe("ready");
    await touch("touchend", 150, 280);
    expect(state()).toBe("refreshing");
    expect(refresh).toHaveBeenCalledOnce();
    await pull();
    expect(refresh).toHaveBeenCalledOnce();
    await act(async () => finish());
    expect(state()).toBe("idle");
  });
  it.each([
    "short",
    "horizontal",
    "upward",
    "edge",
    "scrolled",
    "multi",
    "cancel",
    "reversed",
  ] as const)("does not refresh for %s gestures", async (kind) => {
    if (kind === "scrolled") scroll.scrollTop = 100;
    const x = kind === "edge" ? 8 : 150;
    await touch("touchstart", x, 100);
    if (kind === "horizontal") await touch("touchmove", 300, 120);
    else if (kind === "upward") await touch("touchmove", 150, 50);
    else
      await touch(
        "touchmove",
        x,
        kind === "short" ? 130 : 280,
        kind === "multi" ? 2 : 1,
      );
    if (kind === "reversed") await touch("touchmove", 150, 130);
    await touch(kind === "cancel" ? "touchcancel" : "touchend", x, 280);
    expect(refresh).not.toHaveBeenCalled();
    expect(state()).toBe("idle");
  });
  it("suppresses the row click generated by a drag, while keeping ordinary taps", async () => {
    await pull();
    await act(async () =>
      scroll.querySelector("[data-row]")!.dispatchEvent(
        new MouseEvent("click", {
          bubbles: true,
          cancelable: true,
          detail: 1,
        }),
      ),
    );
    expect(rowClick).not.toHaveBeenCalled();
    await touch("touchstart", 150, 100);
    await touch("touchend", 150, 100);
    await act(async () =>
      scroll
        .querySelector("[data-row]")!
        .dispatchEvent(new MouseEvent("click", { bubbles: true, detail: 1 })),
    );
    expect(rowClick).toHaveBeenCalledOnce();
  });
  it("ends the indicator on failure and allows a later retry", async () => {
    refresh.mockRejectedValueOnce(new Error("offline"));
    await pull();
    expect(state()).toBe("idle");
    expect(node.querySelector('[role="alert"]')?.textContent).toContain(
      "刷新失败",
    );
    await pull();
    expect(refresh).toHaveBeenCalledTimes(2);
    expect(node.querySelector('[role="alert"]')).toBeNull();
  });
  it("offers a keyboard action and ignores duplicate or external loading", async () => {
    await act(async () =>
      node.querySelector<HTMLButtonElement>("button")!.click(),
    );
    expect(refresh).toHaveBeenCalledOnce();
    await act(async () => root.render(<Harness loading />));
    await pull();
    expect(refresh).toHaveBeenCalledOnce();
    expect(node.querySelector<HTMLButtonElement>("button")!.disabled).toBe(
      true,
    );
  });
  it("removes listeners when leaving the list and ignores a late completion", async () => {
    let finish!: () => void;
    refresh.mockImplementation(
      () =>
        new Promise((resolve) => {
          finish = resolve;
        }),
    );
    await pull();
    await act(async () => root.render(<div>Another view</div>));
    await act(async () => finish());
    expect(node.textContent).toBe("Another view");
    await pull();
    expect(refresh).toHaveBeenCalledOnce();
  });
});
