// ============================================================
// Mock Data - 精简导出（完整数据见 data-pipeline 阶段）
// ============================================================

import type { SiteDetail, Region, DynastyInfo, PlatformStats, CalligrapherDetail, CalligrapherSummary, CalligraphyWorkSummary, Relation, GraphData } from './types';
import { Dynasty, Category, ScriptType, ImageRole, RelationType, DYNASTY_ORDER, DYNASTY_YEAR_RANGE } from './enums';

export { DYNASTY_ORDER, DYNASTY_YEAR_RANGE };

export const mockRegions: Region[] = [
  { id: 'r-hunan', parentId: null, name: '湖南省', fullName: '湖南省', level: 'province', administrativeCode: '430000', siteCount: 2, mapCenter: { x: 680, y: 520 } },
  { id: 'r-shandong', parentId: null, name: '山东省', fullName: '山东省', level: 'province', administrativeCode: '370000', siteCount: 2, mapCenter: { x: 740, y: 350 } },
  { id: 'r-shaanxi', parentId: null, name: '陕西省', fullName: '陕西省', level: 'province', administrativeCode: '610000', siteCount: 2, mapCenter: { x: 600, y: 420 } },
  { id: 'r-gansu', parentId: null, name: '甘肃省', fullName: '甘肃省', level: 'province', administrativeCode: '620000', siteCount: 1, mapCenter: { x: 480, y: 380 } },
  { id: 'r-jiangsu', parentId: null, name: '江苏省', fullName: '江苏省', level: 'province', administrativeCode: '320000', siteCount: 1, mapCenter: { x: 740, y: 440 } },
  { id: 'r-hebei', parentId: null, name: '河北省', fullName: '河北省', level: 'province', administrativeCode: '130000', siteCount: 1, mapCenter: { x: 680, y: 310 } },
];

export const mockDynasties: DynastyInfo[] = (Object.entries(DYNASTY_ORDER) as [Dynasty, number][]).map(([name, order]) => ({
  id: `d-${name}`, name, order,
  yearStart: DYNASTY_YEAR_RANGE[name][0],
  yearEnd: DYNASTY_YEAR_RANGE[name][1],
  description: `${name}时期碑刻`, siteCount: 0,
}));

export const mockCalligraphers: CalligrapherDetail[] = [
  { id: 'c-yanzhenqing', name: '颜真卿', courtesyName: '清臣', artName: '颜鲁公', dynasty: Dynasty.TANG, birthYear: 709, deathYear: 785, birthPlace: '京兆万年（陕西西安）', shortBio: '唐代著名书法家，颜体楷书创立者', fullBio: '颜真卿（709-785），唐代名臣、书法家。创"颜体"楷书。', styleDescription: '端庄雄伟，气势开张', achievements: ['创颜体楷书', '楷书四大家之一'], workCount: 12, relatedSites: [], relatedCalligraphers: [], relatedWorks: [], references: [] },
  { id: 'c-yuanjie', name: '元结', courtesyName: '次山', artName: '漫叟', dynasty: Dynasty.TANG, birthYear: 719, deathYear: 772, birthPlace: '河南鲁山', shortBio: '唐代文学家，撰《大唐中兴颂》', fullBio: '元结（719-772），唐代文学家。', styleDescription: '质朴刚健', achievements: ['大唐中兴颂撰文', '开创浯溪碑林'], workCount: 5, relatedSites: [], relatedCalligraphers: [], relatedWorks: [], references: [] },
];

export const mockCalligraphyWorks: CalligraphyWorkSummary[] = [
  { id: 'cw-dtzx', title: '大唐中兴颂', scriptType: ScriptType.REGULAR, style: '颜体楷书', dynasty: Dynasty.TANG, calligrapherName: '颜真卿', currentLocation: '浯溪碑林', siteId: 's-dtzx' },
];

export const mockRelations: Relation[] = [
  { id: 'rel-1', fromType: 'calligrapher', fromId: 'c-yanzhenqing', fromName: '颜真卿', toType: 'site', toId: 's-dtzx', toName: '大唐中兴颂', relationType: RelationType.CALLIGRAPHER, description: '颜真卿书丹《大唐中兴颂》', period: '唐大历六年（771年）', evidence: '碑文记载' },
  { id: 'rel-2', fromType: 'calligrapher', fromId: 'c-yuanjie', fromName: '元结', toType: 'site', toId: 's-dtzx', toName: '大唐中兴颂', relationType: RelationType.WRITER, description: '元结撰文', period: '唐上元二年（761年）', evidence: '碑文记载' },
];

export const mockGraphData: GraphData = {
  nodes: [
    { id: 's-dtzx', label: '大唐中兴颂', type: 'site', dynasty: Dynasty.TANG, group: '碑刻' },
    { id: 's-shimen', label: '石门颂', type: 'site', dynasty: Dynasty.HAN, group: '碑刻' },
    { id: 'c-yanzhenqing', label: '颜真卿', type: 'calligrapher', dynasty: Dynasty.TANG, group: '书家' },
    { id: 'c-yuanjie', label: '元结', type: 'calligrapher', dynasty: Dynasty.TANG, group: '书家' },
    { id: 'cw-dtzx', label: '大唐中兴颂', type: 'work', dynasty: Dynasty.TANG, group: '作品' },
  ],
  edges: [
    { id: 'e-1', source: 'c-yanzhenqing', target: 's-dtzx', label: RelationType.CALLIGRAPHER, relationType: '书丹' },
    { id: 'e-2', source: 'c-yuanjie', target: 's-dtzx', label: RelationType.WRITER, relationType: '撰文' },
    { id: 'e-3', source: 'cw-dtzx', target: 's-dtzx', label: RelationType.RELATED, relationType: '关联' },
  ],
};

function imgKeys(siteCode: string, imageId: string) {
  return {
    objectKey: `sites/${siteCode}/images/${imageId}.webp`,
    thumbnailKey: `sites/${siteCode}/thumbnail/${imageId}.webp`,
    displayKey: `sites/${siteCode}/display/${imageId}.webp`,
    originalKey: `archive/${siteCode}/original/${imageId}.tif`,
  };
}

const coverThumb = (id: string) => `https://placehold.co/400x300/F5F0E8/2C2C2C?text=${encodeURIComponent(id)}`;

export const mockSites: SiteDetail[] = [
  {
    id: 's-dtzx', siteCode: 'HN-QY-001', slug: 'datang-zhongxing-song',
    title: '大唐中兴颂', fullTitle: '大唐中兴颂摩崖石刻', alias: ['中兴颂'],
    dynasty: Dynasty.TANG, dynastyYear: '唐大历六年（771年）', category: Category.CLIFF_INSCRIPTION, scriptType: ScriptType.REGULAR,
    calligrapher: '颜真卿', engraver: '佚名', inscriber: '元结',
    region: { province: '湖南省', city: '永州市', county: '祁阳市' },
    summary: '唐代元结撰文、颜真卿书丹的大型摩崖石刻，被誉为"摩崖三绝"。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=大唐中兴颂', coverThumbnail: coverThumb('大唐中兴颂'),
    tags: ['颜真卿', '元结', '楷书', '唐代名碑', '浯溪碑林'],
    pinyinIndex: 'datangzhongxingsong dtzxs', publicationStatus: 'published',
    location: { latitude: 26.58, longitude: 111.85, coordinateSystem: 'WGS84', precision: 'exact', address: '湖南省永州市祁阳市浯溪碑林' },
    dimensions: '高284厘米，宽350厘米', wordCount: 332,
    preservationStatus: '整体保存完好', investigationDate: '2024年3月',
    calligraphyFeatures: {
      brushwork: '颜真卿晚年力作，笔力沉雄，中锋用笔，横细竖粗特征鲜明。',
      structure: '结体宽博方正，左右对称，气势开张。',
      composition: '章法严谨，字距行距均匀，整篇气韵贯通。',
      style: '颜体楷书成熟期代表作，端庄雄伟，气势磅礴。',
      features: '用笔圆转藏锋，提按分明；结体外拓，有蚕头燕尾之势。',
      significance: '被誉为"颜书第一"，是研究唐代书法的重要史料。',
    },
    fullDescription: '《大唐中兴颂》由元结撰文，大历六年颜真卿书丹刻于浯溪崖壁。全文332字。世称"摩崖三绝"。',
    researchNotes: '宋代黄庭坚等曾来此题咏。全国重点文物保护单位。',
    images: [
      { ...imgKeys('HN-QY-001', 'img-001'), id: 'img-001', siteId: 's-dtzx', caption: '大唐中兴颂全景', description: '浯溪崖壁石刻', imageType: ImageRole.COVER, sortOrder: 1, width: 4000, height: 3200, fileSize: 2450000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'a'.repeat(64), uploadedAt: '2024-06-01T10:00:00Z' },
    ],
    references: [{ id: 'ref-1', title: '浯溪碑林石刻研究', author: '陈振濂', year: 2018, sourceType: '专著', publisher: '中华书局', citationText: '陈振濂. 浯溪碑林石刻研究[M]. 中华书局, 2018.' }],
    relatedSites: [], calligraphers: [
      { id: 'c-yanzhenqing', name: '颜真卿', courtesyName: '清臣', artName: '颜鲁公', dynasty: Dynasty.TANG, shortBio: '唐代著名书法家', workCount: 12 },
    ],
    calligraphyWorks: [{ id: 'cw-dtzx', title: '大唐中兴颂', scriptType: ScriptType.REGULAR, style: '颜体楷书', dynasty: Dynasty.TANG, calligrapherName: '颜真卿', currentLocation: '浯溪碑林', siteId: 's-dtzx' }],
    seoTitle: '大唐中兴颂 - 颜真卿楷书摩崖石刻', seoDescription: '唐代颜真卿书丹的大唐中兴颂摩崖石刻。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-shimen', siteCode: 'SX-HZ-001', slug: 'shimen-song',
    title: '石门颂', fullTitle: '故司隶校尉犍为杨君颂', alias: ['汉隶极则'],
    dynasty: Dynasty.HAN, dynastyYear: '东汉建和二年（148年）', category: Category.CLIFF_INSCRIPTION, scriptType: ScriptType.CLERICAL,
    calligrapher: '王戒', engraver: '佚名', inscriber: '王升',
    region: { province: '陕西省', city: '汉中市', county: '勉县' },
    summary: '东汉隶书摩崖石刻，记载杨孟文修凿石门道之事，被誉为"汉隶极则"。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=石门颂', coverThumbnail: coverThumb('石门颂'),
    tags: ['隶书', '汉代', '汉中', '石门十三品'],
    pinyinIndex: 'shimensong sms', publicationStatus: 'published',
    location: { latitude: 33.15, longitude: 106.68, coordinateSystem: 'WGS84', precision: 'exact', address: '陕西省汉中市勉县褒城镇' },
    dimensions: '高261厘米，宽205厘米', wordCount: 655,
    preservationStatus: '已移至汉中市博物馆保存', investigationDate: '2023年10月',
    calligraphyFeatures: {
      brushwork: '逆锋起笔，回锋收笔，笔画舒展飘逸。',
      structure: '结体舒展自然，纵逸奔放。',
      composition: '章法疏朗，气韵流动。',
      style: '汉隶中最为纵逸奔放者。',
      features: '笔画瘦劲飘逸，波挑明显。',
      significance: '汉隶三大名碑之一。',
    },
    fullDescription: '《石门颂》刻于东汉建和二年（148年），记述杨孟文修凿石门道的功绩。1971年移至汉中市博物馆。',
    researchNotes: '与《郙阁颂》、《西狭颂》并称"汉三颂"。',
    images: [{ ...imgKeys('SX-HZ-001', 'img-002'), id: 'img-002', siteId: 's-shimen', caption: '石门颂全景', description: '石门颂整拓', imageType: ImageRole.COVER, sortOrder: 1, width: 3500, height: 4500, fileSize: 3200000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'b'.repeat(64), uploadedAt: '2024-06-01T11:00:00Z' }],
    references: [{ id: 'ref-2', title: '汉石门颂研究', author: '刘正成', year: 2005, sourceType: '专著', publisher: '荣宝斋出版社', citationText: '刘正成. 汉石门颂研究[M]. 荣宝斋出版社, 2005.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '石门颂 - 东汉隶书摩崖石刻', seoDescription: '石门颂是东汉隶书摩崖石刻，汉隶极则。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-yhming', siteCode: 'JS-ZJ-001', slug: 'yi-he-ming',
    title: '瘗鹤铭', fullTitle: '瘗鹤铭摩崖石刻', alias: ['大字之祖'],
    dynasty: Dynasty.NORTHERN_SOUTHERN, dynastyYear: '南朝梁（约514年）', category: Category.CLIFF_INSCRIPTION, scriptType: ScriptType.REGULAR,
    calligrapher: '陶弘景（传）', engraver: '佚名', inscriber: '佚名',
    region: { province: '江苏省', city: '镇江市', county: '京口区' },
    summary: '南朝摩崖石刻，被誉为"大字之祖"。书法气势宏逸。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=瘗鹤铭', coverThumbnail: coverThumb('瘗鹤铭'),
    tags: ['大字之祖', '南朝', '焦山'],
    pinyinIndex: 'yiheming yhm', publicationStatus: 'published',
    location: { latitude: 32.22, longitude: 119.47, coordinateSystem: 'WGS84', precision: 'exact', address: '江苏省镇江市焦山碑林' },
    dimensions: '原石高约200厘米', wordCount: 167,
    preservationStatus: '原石曾坠落江中，残石现存焦山碑林', investigationDate: '2023年8月',
    calligraphyFeatures: {
      brushwork: '笔力雄健，中锋为主。',
      structure: '结体内紧外松，气势宏大。',
      composition: '章法自然疏朗。',
      style: '楷书而有隶意，古拙雄浑。',
      features: '大字榜书典范。',
      significance: '大字榜书最高典范。',
    },
    fullDescription: '《瘗鹤铭》是南朝摩崖石刻，原刻于焦山西麓崖壁。铭文悼念仙鹤。宋代坠落江中，清代打捞残石。',
    researchNotes: '黄庭坚盛赞"大字无过瘗鹤铭"。',
    images: [{ ...imgKeys('JS-ZJ-001', 'img-003'), id: 'img-003', siteId: 's-yhming', caption: '瘗鹤铭残石', description: '焦山碑林藏', imageType: ImageRole.COVER, sortOrder: 1, width: 3000, height: 4000, fileSize: 2800000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'c'.repeat(64), uploadedAt: '2024-06-01T12:00:00Z' }],
    references: [{ id: 'ref-3', title: '瘗鹤铭研究', author: '水赉佑', year: 2010, sourceType: '论文', citationText: '水赉佑. 瘗鹤铭研究[J]. 书法研究, 2010.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '瘗鹤铭 - 大字之祖', seoDescription: '瘗鹤铭是南朝摩崖石刻，被誉为大字之祖。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-xixia', siteCode: 'GS-LN-001', slug: 'xi-xia-song',
    title: '西狭颂', fullTitle: '汉武都太守李翕西狭颂', alias: ['惠安西表'],
    dynasty: Dynasty.HAN, dynastyYear: '东汉建宁四年（171年）', category: Category.CLIFF_INSCRIPTION, scriptType: ScriptType.CLERICAL,
    calligrapher: '仇靖', engraver: '仇靖', inscriber: '仇靖',
    region: { province: '甘肃省', city: '陇南市', county: '成县' },
    summary: '东汉隶书摩崖石刻，与石门颂、郙阁颂并称"汉三颂"。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=西狭颂', coverThumbnail: coverThumb('西狭颂'),
    tags: ['隶书', '汉代', '汉三颂', '陇南'],
    pinyinIndex: 'xixiasong xxs', publicationStatus: 'published',
    location: { latitude: 33.75, longitude: 105.75, coordinateSystem: 'WGS84', precision: 'exact', address: '甘肃省陇南市成县西狭颂景区' },
    dimensions: '高148厘米，宽148厘米', wordCount: 385,
    preservationStatus: '保存完好', investigationDate: '2023年5月',
    calligraphyFeatures: { brushwork: '古朴厚重，方整匀称。', structure: '方正严谨，端庄大度。', composition: '布局规整。', style: '汉隶成熟期代表作。', features: '保存最完好的汉隶摩崖。', significance: '学习汉隶最佳范本。' },
    fullDescription: '《西狭颂》刻于东汉建宁四年（171年），记述武都太守李翕修治西狭栈道之功。',
    researchNotes: '汉三颂中保存最完好者。',
    images: [{ ...imgKeys('GS-LN-001', 'img-004'), id: 'img-004', siteId: 's-xixia', caption: '西狭颂全景', description: '西狭颂摩崖石刻', imageType: ImageRole.COVER, sortOrder: 1, width: 3000, height: 3000, fileSize: 2100000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'd'.repeat(64), uploadedAt: '2024-06-01T13:00:00Z' }],
    references: [{ id: 'ref-4', title: '汉三颂研究', author: '华人德', year: 1995, sourceType: '专著', citationText: '华人德. 汉三颂研究[M]. 1995.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '西狭颂 - 东汉隶书摩崖', seoDescription: '西狭颂是东汉隶书摩崖石刻，汉三颂之一。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-zhenwengong', siteCode: 'SD-LY-001', slug: 'zheng-wengong-bei',
    title: '郑文公碑', fullTitle: '魏故中书令郑文公之碑', alias: ['郑文公下碑'],
    dynasty: Dynasty.NORTHERN_SOUTHERN, dynastyYear: '北魏永平四年（511年）', category: Category.CLIFF_INSCRIPTION, scriptType: ScriptType.REGULAR,
    calligrapher: '郑道昭', engraver: '佚名', inscriber: '郑道昭',
    region: { province: '山东省', city: '烟台市', county: '莱州市' },
    summary: '北魏摩崖石刻，郑道昭为其父郑羲所立，魏碑代表作。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=郑文公碑', coverThumbnail: coverThumb('郑文公碑'),
    tags: ['魏碑', '北魏', '郑道昭', '云峰山'],
    pinyinIndex: 'zhengwengongbei zwgb', publicationStatus: 'published',
    location: { latitude: 37.18, longitude: 119.93, coordinateSystem: 'WGS84', precision: 'exact', address: '山东省烟台市莱州市云峰山' },
    dimensions: '高195厘米，宽367厘米', wordCount: 1244,
    preservationStatus: '有风化，大体可辨识', investigationDate: '2023年7月',
    calligraphyFeatures: { brushwork: '方圆兼备，以圆为主。', structure: '宽博舒展。', composition: '规整中见灵动。', style: '魏碑圆笔代表。', features: '开隋唐楷书先声。', significance: '北朝摩崖刻石代表。' },
    fullDescription: '《郑文公碑》刻于北魏永平四年（511年），郑道昭为其父郑羲所立。全文1244字。',
    researchNotes: '清代包世臣、康有为极力推崇。',
    images: [{ ...imgKeys('SD-LY-001', 'img-005'), id: 'img-005', siteId: 's-zhenwengong', caption: '郑文公下碑', description: '云峰山郑文公碑', imageType: ImageRole.COVER, sortOrder: 1, width: 5000, height: 2700, fileSize: 3500000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'e'.repeat(64), uploadedAt: '2024-06-01T14:00:00Z' }],
    references: [{ id: 'ref-5', title: '郑道昭与云峰刻石', author: '刘涛', year: 2008, sourceType: '专著', citationText: '刘涛. 郑道昭与云峰刻石[M]. 2008.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '郑文公碑 - 北魏摩崖魏碑', seoDescription: '郑文公碑是北魏摩崖石刻，魏碑代表作。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-jingshiyu', siteCode: 'SD-TA-001', slug: 'taishan-jingshiyu',
    title: '泰山经石峪', fullTitle: '泰山经石峪金刚经摩崖刻石', alias: ['大字鼻祖', '榜书之宗'],
    dynasty: Dynasty.NORTHERN_SOUTHERN, dynastyYear: '北齐（约550-577年）', category: Category.SUTRA, scriptType: ScriptType.CLERICAL,
    calligrapher: '安道壹（传）', engraver: '佚名', inscriber: '佚名',
    region: { province: '山东省', city: '泰安市', county: '泰山区' },
    summary: '北齐摩崖刻经，字径达50厘米，被誉为"大字鼻祖""榜书之宗"。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=泰山经石峪', coverThumbnail: coverThumb('泰山经石峪'),
    tags: ['刻经', '北齐', '泰山', '大字鼻祖'],
    pinyinIndex: 'taishanjingshiyu tsjsy', publicationStatus: 'published',
    location: { latitude: 36.25, longitude: 117.10, coordinateSystem: 'WGS84', precision: 'exact', address: '山东省泰安市泰山经石峪' },
    dimensions: '刻面约2000平方米', wordCount: 1069,
    preservationStatus: '部分风化', investigationDate: '2023年9月',
    calligraphyFeatures: { brushwork: '圆融浑厚，隶楷之间。', structure: '宽绰雍容，端庄大度。', composition: '因石就形，浑然天成。', style: '大字鼻祖，榜书之宗。', features: '字径50厘米，现存最大摩崖刻经。', significance: '大字榜书巅峰之作。' },
    fullDescription: '泰山经石峪刻有《金刚经》全文，字径约50厘米，是现存最大的摩崖刻经。',
    researchNotes: '杨守敬评"擘窠大字，此为极则"。',
    images: [{ ...imgKeys('SD-TA-001', 'img-006'), id: 'img-006', siteId: 's-jingshiyu', caption: '经石峪全景', description: '泰山经石峪刻经', imageType: ImageRole.COVER, sortOrder: 1, width: 5000, height: 3300, fileSize: 4200000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'f'.repeat(64), uploadedAt: '2024-06-01T15:00:00Z' }],
    references: [{ id: 'ref-6', title: '泰山经石峪研究', author: '赖非', year: 2003, sourceType: '专著', citationText: '赖非. 泰山经石峪研究[M]. 2003.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '泰山经石峪 - 大字鼻祖', seoDescription: '泰山经石峪是北齐摩崖刻经，字径50厘米。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-longcangsi', siteCode: 'HE-SJ-001', slug: 'longcangsi-bei',
    title: '龙藏寺碑', fullTitle: '恒州刺史鄂国公为国劝造龙藏寺碑', alias: ['隋碑第一'],
    dynasty: Dynasty.SUI, dynastyYear: '隋开皇六年（586年）', category: Category.STELE, scriptType: ScriptType.REGULAR,
    calligrapher: '佚名', engraver: '佚名', inscriber: '张公礼',
    region: { province: '河北省', city: '石家庄市', county: '正定县' },
    summary: '隋代楷书碑刻，被誉为"隋碑第一"，隶楷过渡时期的代表作。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=龙藏寺碑', coverThumbnail: coverThumb('龙藏寺碑'),
    tags: ['隋碑', '楷书', '隋碑第一', '正定'],
    pinyinIndex: 'longcangsibei lcsb', publicationStatus: 'published',
    location: { latitude: 38.13, longitude: 114.56, coordinateSystem: 'WGS84', precision: 'exact', address: '河北省石家庄市正定县隆兴寺' },
    dimensions: '高210厘米，宽90厘米', wordCount: 1500,
    preservationStatus: '保存良好', investigationDate: '2023年6月',
    calligraphyFeatures: { brushwork: '瘦劲有力，方圆兼备。', structure: '内紧外松，平正有变。', composition: '布局整齐。', style: '隶楷过渡典范。', features: '上承汉隶，下启唐楷。', significance: '隋代楷书最高成就。' },
    fullDescription: '《龙藏寺碑》刻于隋开皇六年（586年），记述王孝仙劝造龙藏寺之事。',
    researchNotes: '康有为评为"隋碑第一"。现存正定隆兴寺。',
    images: [{ ...imgKeys('HE-SJ-001', 'img-007'), id: 'img-007', siteId: 's-longcangsi', caption: '龙藏寺碑', description: '隆兴寺藏', imageType: ImageRole.COVER, sortOrder: 1, width: 2400, height: 5600, fileSize: 2900000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'a1'.repeat(32), uploadedAt: '2024-06-01T16:00:00Z' }],
    references: [{ id: 'ref-7', title: '隋龙藏寺碑研究', author: '王连起', year: 2000, sourceType: '论文', citationText: '王连起. 隋龙藏寺碑研究[J]. 2000.' }],
    relatedSites: [], calligraphers: [], calligraphyWorks: [],
    seoTitle: '龙藏寺碑 - 隋碑第一', seoDescription: '龙藏寺碑是隋代楷书碑刻，隋碑第一。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 's-duobaota', siteCode: 'SX-XA-001', slug: 'duobaota-bei',
    title: '多宝塔碑', fullTitle: '大唐西京千福寺多宝佛塔感应碑', alias: ['多宝塔感应碑'],
    dynasty: Dynasty.TANG, dynastyYear: '唐天宝十一载（752年）', category: Category.STELE, scriptType: ScriptType.REGULAR,
    calligrapher: '颜真卿', engraver: '史华', inscriber: '岑勋',
    region: { province: '陕西省', city: '西安市', county: '碑林区' },
    summary: '唐代颜真卿楷书碑刻，是学习楷书的经典范本。',
    coverImage: 'https://placehold.co/800x600/F5F0E8/2C2C2C?text=多宝塔碑', coverThumbnail: coverThumb('多宝塔碑'),
    tags: ['颜真卿', '楷书', '唐代', '西安碑林'],
    pinyinIndex: 'duobaotabei dbtb', publicationStatus: 'published',
    location: { latitude: 34.25, longitude: 108.95, coordinateSystem: 'WGS84', precision: 'exact', address: '陕西省西安市碑林区西安碑林博物馆' },
    dimensions: '高285厘米，宽102厘米', wordCount: 2027,
    preservationStatus: '保存完好', investigationDate: '2023年4月',
    calligraphyFeatures: { brushwork: '清劲秀丽，严谨不苟。', structure: '匀整方正，端庄大方。', composition: '布局规整，行列分明。', style: '颜真卿早期楷书典范。', features: '初学楷书最佳范本。', significance: '颜体入门必学。' },
    fullDescription: '《多宝塔碑》唐天宝十一载（752年）立，颜真卿44岁书。现存西安碑林。',
    researchNotes: '与《颜勤礼碑》等并为颜体经典。',
    images: [{ ...imgKeys('SX-XA-001', 'img-008'), id: 'img-008', siteId: 's-duobaota', caption: '多宝塔碑', description: '西安碑林藏', imageType: ImageRole.COVER, sortOrder: 1, width: 2600, height: 7200, fileSize: 4100000, format: 'webp', annotations: [], publicationStatus: 'published', sha256: 'b1'.repeat(32), uploadedAt: '2024-06-01T17:00:00Z' }],
    references: [{ id: 'ref-8', title: '颜真卿书法全集', author: '朱关田', year: 1993, sourceType: '专著', citationText: '朱关田. 颜真卿书法全集[M]. 1993.' }],
    relatedSites: [], calligraphers: [{ id: 'c-yanzhenqing', name: '颜真卿', courtesyName: '清臣', artName: '颜鲁公', dynasty: Dynasty.TANG, shortBio: '唐代著名书法家', workCount: 12 }],
    calligraphyWorks: [{ id: 'cw-dtzx', title: '大唐中兴颂', scriptType: ScriptType.REGULAR, style: '颜体楷书', dynasty: Dynasty.TANG, calligrapherName: '颜真卿', currentLocation: '浯溪碑林', siteId: 's-dtzx' }],
    seoTitle: '多宝塔碑 - 颜真卿楷书经典', seoDescription: '多宝塔碑是颜真卿楷书经典，入门必学。',
    createdAt: '2024-06-01T00:00:00Z', updatedAt: '2024-06-01T00:00:00Z',
  },
];

export const mockStats: PlatformStats = {
  totalSites: mockSites.length, totalProvinces: 6, totalImages: 8, totalCalligraphers: 2, totalWorks: 1,
  dynastyDistribution: [{ dynasty: Dynasty.TANG, count: 2 }, { dynasty: Dynasty.HAN, count: 2 }, { dynasty: Dynasty.NORTHERN_SOUTHERN, count: 3 }, { dynasty: Dynasty.SUI, count: 1 }],
  categoryDistribution: [{ category: Category.CLIFF_INSCRIPTION, count: 5 }, { category: Category.STELE, count: 2 }, { category: Category.SUTRA, count: 1 }],
  scriptTypeDistribution: [{ scriptType: ScriptType.REGULAR, count: 5 }, { scriptType: ScriptType.CLERICAL, count: 3 }],
  provinceDistribution: [{ province: '山东省', count: 2 }, { province: '湖南省', count: 1 }, { province: '陕西省', count: 2 }, { province: '甘肃省', count: 1 }, { province: '江苏省', count: 1 }, { province: '河北省', count: 1 }],
  recentUpdates: mockSites.slice(0, 3),
};
