import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres";
// Generated by `payload migrate:create`; the eleven `users.agent_principal` and
// `payload_mcp_api_keys` drift statements that the 20260917 hand-written
// migration already applied were removed by hand, since the previous snapshot
// did not record them.

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_articles_presentation" AS ENUM('news', 'academic');
  CREATE TYPE "public"."enum_articles_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__articles_v_version_presentation" AS ENUM('news', 'academic');
  CREATE TYPE "public"."enum__articles_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_article_collections_members_kind" AS ENUM('article', 'catalog');
  CREATE TYPE "public"."enum_article_collections_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__article_collections_v_version_members_kind" AS ENUM('article', 'catalog');
  CREATE TYPE "public"."enum__article_collections_v_version_status" AS ENUM('draft', 'published');
  CREATE TABLE "articles_sections" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"body" varchar,
  	"image_catalog_id" integer,
  	"image_caption" varchar
  );
  
  CREATE TABLE "articles_citations" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"text" varchar,
  	"url" varchar
  );
  
  CREATE TABLE "articles" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"last_edited_by_id" integer,
  	"revision" numeric DEFAULT 0,
  	"article_id" varchar,
  	"first_published_at" timestamp(3) with time zone,
  	"published_at" timestamp(3) with time zone,
  	"presentation" "enum_articles_presentation" DEFAULT 'news',
  	"title" varchar,
  	"subtitle" varchar,
  	"summary" varchar,
  	"section" varchar,
  	"issue" varchar,
  	"byline" varchar,
  	"cover_catalog_id" integer,
  	"cover_alt" varchar,
  	"intro" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_articles_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "_articles_v_version_sections" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"body" varchar,
  	"image_catalog_id" integer,
  	"image_caption" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_articles_v_version_citations" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"text" varchar,
  	"url" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_articles_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_last_edited_by_id" integer,
  	"version_revision" numeric DEFAULT 0,
  	"version_article_id" varchar,
  	"version_first_published_at" timestamp(3) with time zone,
  	"version_published_at" timestamp(3) with time zone,
  	"version_presentation" "enum__articles_v_version_presentation" DEFAULT 'news',
  	"version_title" varchar,
  	"version_subtitle" varchar,
  	"version_summary" varchar,
  	"version_section" varchar,
  	"version_issue" varchar,
  	"version_byline" varchar,
  	"version_cover_catalog_id" integer,
  	"version_cover_alt" varchar,
  	"version_intro" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__articles_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean,
  	"autosave" boolean
  );
  
  CREATE TABLE "article_collections_members" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"kind" "enum_article_collections_members_kind" DEFAULT 'article',
  	"article_id" integer,
  	"catalog_id" varchar
  );
  
  CREATE TABLE "article_collections" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"last_edited_by_id" integer,
  	"revision" numeric DEFAULT 0,
  	"collection_id" varchar,
  	"first_published_at" timestamp(3) with time zone,
  	"published_at" timestamp(3) with time zone,
  	"title" varchar,
  	"subtitle" varchar,
  	"summary" varchar,
  	"category" varchar,
  	"issue" varchar,
  	"cover_catalog_id" integer,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_article_collections_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "_article_collections_v_version_members" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"kind" "enum__article_collections_v_version_members_kind" DEFAULT 'article',
  	"article_id" integer,
  	"catalog_id" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_article_collections_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_last_edited_by_id" integer,
  	"version_revision" numeric DEFAULT 0,
  	"version_collection_id" varchar,
  	"version_first_published_at" timestamp(3) with time zone,
  	"version_published_at" timestamp(3) with time zone,
  	"version_title" varchar,
  	"version_subtitle" varchar,
  	"version_summary" varchar,
  	"version_category" varchar,
  	"version_issue" varchar,
  	"version_cover_catalog_id" integer,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__article_collections_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean,
  	"autosave" boolean
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "articles_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "article_collections_id" integer;
  ALTER TABLE "articles_sections" ADD CONSTRAINT "articles_sections_image_catalog_id_catalogs_id_fk" FOREIGN KEY ("image_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "articles_sections" ADD CONSTRAINT "articles_sections_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_citations" ADD CONSTRAINT "articles_citations_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles" ADD CONSTRAINT "articles_last_edited_by_id_users_id_fk" FOREIGN KEY ("last_edited_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "articles" ADD CONSTRAINT "articles_cover_catalog_id_catalogs_id_fk" FOREIGN KEY ("cover_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_articles_v_version_sections" ADD CONSTRAINT "_articles_v_version_sections_image_catalog_id_catalogs_id_fk" FOREIGN KEY ("image_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_articles_v_version_sections" ADD CONSTRAINT "_articles_v_version_sections_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_articles_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_articles_v_version_citations" ADD CONSTRAINT "_articles_v_version_citations_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_articles_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_articles_v" ADD CONSTRAINT "_articles_v_parent_id_articles_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."articles"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_articles_v" ADD CONSTRAINT "_articles_v_version_last_edited_by_id_users_id_fk" FOREIGN KEY ("version_last_edited_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_articles_v" ADD CONSTRAINT "_articles_v_version_cover_catalog_id_catalogs_id_fk" FOREIGN KEY ("version_cover_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "article_collections_members" ADD CONSTRAINT "article_collections_members_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "article_collections_members" ADD CONSTRAINT "article_collections_members_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."article_collections"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "article_collections" ADD CONSTRAINT "article_collections_last_edited_by_id_users_id_fk" FOREIGN KEY ("last_edited_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "article_collections" ADD CONSTRAINT "article_collections_cover_catalog_id_catalogs_id_fk" FOREIGN KEY ("cover_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_article_collections_v_version_members" ADD CONSTRAINT "_article_collections_v_version_members_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_article_collections_v_version_members" ADD CONSTRAINT "_article_collections_v_version_members_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_article_collections_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_article_collections_v" ADD CONSTRAINT "_article_collections_v_parent_id_article_collections_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."article_collections"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_article_collections_v" ADD CONSTRAINT "_article_collections_v_version_last_edited_by_id_users_id_fk" FOREIGN KEY ("version_last_edited_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_article_collections_v" ADD CONSTRAINT "_article_collections_v_version_cover_catalog_id_catalogs_id_fk" FOREIGN KEY ("version_cover_catalog_id") REFERENCES "public"."catalogs"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "articles_sections_order_idx" ON "articles_sections" USING btree ("_order");
  CREATE INDEX "articles_sections_parent_id_idx" ON "articles_sections" USING btree ("_parent_id");
  CREATE INDEX "articles_sections_image_catalog_idx" ON "articles_sections" USING btree ("image_catalog_id");
  CREATE INDEX "articles_citations_order_idx" ON "articles_citations" USING btree ("_order");
  CREATE INDEX "articles_citations_parent_id_idx" ON "articles_citations" USING btree ("_parent_id");
  CREATE INDEX "articles_last_edited_by_idx" ON "articles" USING btree ("last_edited_by_id");
  CREATE UNIQUE INDEX "articles_article_id_idx" ON "articles" USING btree ("article_id");
  CREATE INDEX "articles_cover_catalog_idx" ON "articles" USING btree ("cover_catalog_id");
  CREATE INDEX "articles_updated_at_idx" ON "articles" USING btree ("updated_at");
  CREATE INDEX "articles_created_at_idx" ON "articles" USING btree ("created_at");
  CREATE INDEX "articles__status_idx" ON "articles" USING btree ("_status");
  CREATE INDEX "_articles_v_version_sections_order_idx" ON "_articles_v_version_sections" USING btree ("_order");
  CREATE INDEX "_articles_v_version_sections_parent_id_idx" ON "_articles_v_version_sections" USING btree ("_parent_id");
  CREATE INDEX "_articles_v_version_sections_image_catalog_idx" ON "_articles_v_version_sections" USING btree ("image_catalog_id");
  CREATE INDEX "_articles_v_version_citations_order_idx" ON "_articles_v_version_citations" USING btree ("_order");
  CREATE INDEX "_articles_v_version_citations_parent_id_idx" ON "_articles_v_version_citations" USING btree ("_parent_id");
  CREATE INDEX "_articles_v_parent_idx" ON "_articles_v" USING btree ("parent_id");
  CREATE INDEX "_articles_v_version_version_last_edited_by_idx" ON "_articles_v" USING btree ("version_last_edited_by_id");
  CREATE INDEX "_articles_v_version_version_article_id_idx" ON "_articles_v" USING btree ("version_article_id");
  CREATE INDEX "_articles_v_version_version_cover_catalog_idx" ON "_articles_v" USING btree ("version_cover_catalog_id");
  CREATE INDEX "_articles_v_version_version_updated_at_idx" ON "_articles_v" USING btree ("version_updated_at");
  CREATE INDEX "_articles_v_version_version_created_at_idx" ON "_articles_v" USING btree ("version_created_at");
  CREATE INDEX "_articles_v_version_version__status_idx" ON "_articles_v" USING btree ("version__status");
  CREATE INDEX "_articles_v_created_at_idx" ON "_articles_v" USING btree ("created_at");
  CREATE INDEX "_articles_v_updated_at_idx" ON "_articles_v" USING btree ("updated_at");
  CREATE INDEX "_articles_v_latest_idx" ON "_articles_v" USING btree ("latest");
  CREATE INDEX "_articles_v_autosave_idx" ON "_articles_v" USING btree ("autosave");
  CREATE INDEX "article_collections_members_order_idx" ON "article_collections_members" USING btree ("_order");
  CREATE INDEX "article_collections_members_parent_id_idx" ON "article_collections_members" USING btree ("_parent_id");
  CREATE INDEX "article_collections_members_article_idx" ON "article_collections_members" USING btree ("article_id");
  CREATE INDEX "article_collections_last_edited_by_idx" ON "article_collections" USING btree ("last_edited_by_id");
  CREATE UNIQUE INDEX "article_collections_collection_id_idx" ON "article_collections" USING btree ("collection_id");
  CREATE INDEX "article_collections_cover_catalog_idx" ON "article_collections" USING btree ("cover_catalog_id");
  CREATE INDEX "article_collections_updated_at_idx" ON "article_collections" USING btree ("updated_at");
  CREATE INDEX "article_collections_created_at_idx" ON "article_collections" USING btree ("created_at");
  CREATE INDEX "article_collections__status_idx" ON "article_collections" USING btree ("_status");
  CREATE INDEX "_article_collections_v_version_members_order_idx" ON "_article_collections_v_version_members" USING btree ("_order");
  CREATE INDEX "_article_collections_v_version_members_parent_id_idx" ON "_article_collections_v_version_members" USING btree ("_parent_id");
  CREATE INDEX "_article_collections_v_version_members_article_idx" ON "_article_collections_v_version_members" USING btree ("article_id");
  CREATE INDEX "_article_collections_v_parent_idx" ON "_article_collections_v" USING btree ("parent_id");
  CREATE INDEX "_article_collections_v_version_version_last_edited_by_idx" ON "_article_collections_v" USING btree ("version_last_edited_by_id");
  CREATE INDEX "_article_collections_v_version_version_collection_id_idx" ON "_article_collections_v" USING btree ("version_collection_id");
  CREATE INDEX "_article_collections_v_version_version_cover_catalog_idx" ON "_article_collections_v" USING btree ("version_cover_catalog_id");
  CREATE INDEX "_article_collections_v_version_version_updated_at_idx" ON "_article_collections_v" USING btree ("version_updated_at");
  CREATE INDEX "_article_collections_v_version_version_created_at_idx" ON "_article_collections_v" USING btree ("version_created_at");
  CREATE INDEX "_article_collections_v_version_version__status_idx" ON "_article_collections_v" USING btree ("version__status");
  CREATE INDEX "_article_collections_v_created_at_idx" ON "_article_collections_v" USING btree ("created_at");
  CREATE INDEX "_article_collections_v_updated_at_idx" ON "_article_collections_v" USING btree ("updated_at");
  CREATE INDEX "_article_collections_v_latest_idx" ON "_article_collections_v" USING btree ("latest");
  CREATE INDEX "_article_collections_v_autosave_idx" ON "_article_collections_v" USING btree ("autosave");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_articles_fk" FOREIGN KEY ("articles_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_article_collections_fk" FOREIGN KEY ("article_collections_id") REFERENCES "public"."article_collections"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_articles_id_idx" ON "payload_locked_documents_rels" USING btree ("articles_id");
  CREATE INDEX "payload_locked_documents_rels_article_collections_id_idx" ON "payload_locked_documents_rels" USING btree ("article_collections_id");`);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "articles_sections" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "articles_citations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "articles" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_articles_v_version_sections" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_articles_v_version_citations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_articles_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "article_collections_members" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "article_collections" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_article_collections_v_version_members" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_article_collections_v" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "articles_sections" CASCADE;
  DROP TABLE "articles_citations" CASCADE;
  DROP TABLE "articles" CASCADE;
  DROP TABLE "_articles_v_version_sections" CASCADE;
  DROP TABLE "_articles_v_version_citations" CASCADE;
  DROP TABLE "_articles_v" CASCADE;
  DROP TABLE "article_collections_members" CASCADE;
  DROP TABLE "article_collections" CASCADE;
  DROP TABLE "_article_collections_v_version_members" CASCADE;
  DROP TABLE "_article_collections_v" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_articles_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_article_collections_fk";
  
  DROP INDEX "payload_locked_documents_rels_articles_id_idx";
  DROP INDEX "payload_locked_documents_rels_article_collections_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "articles_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "article_collections_id";
  DROP TYPE "public"."enum_articles_presentation";
  DROP TYPE "public"."enum_articles_status";
  DROP TYPE "public"."enum__articles_v_version_presentation";
  DROP TYPE "public"."enum__articles_v_version_status";
  DROP TYPE "public"."enum_article_collections_members_kind";
  DROP TYPE "public"."enum_article_collections_status";
  DROP TYPE "public"."enum__article_collections_v_version_members_kind";
  DROP TYPE "public"."enum__article_collections_v_version_status";`);
}
